=== opencadc/science-platform/skaha/src/test/resources/context-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "ResourceConfiguration",
  "type": "object",
  "properties": {
    "cores": {
      "type": "object",
      "properties": {
        "default": { "type": "integer", "description": "Default selection on the Science Portal form." },
        "defaultRequest": { "type": "integer" },
        "defaultLimit": { "type": "integer" },
        "options": {
          "type": "array",
          "items": { "type": "integer" },
          "minItems": 1
        }
      },
      "required": ["defaultRequest", "defaultLimit", "options"],
      "additionalProperties": false
    },
    "memoryGB": {
      "type": "object",
      "properties": {
        "default": { "type": "integer", "description": "Default selection on the Science Portal form." },
        "defaultRequest": { "type": "integer" },
        "defaultLimit": { "type": "integer" },
        "options": {
          "type": "array",
          "items": { "type": "integer" },
          "minItems": 1
        }
      },
      "required": ["defaultRequest", "defaultLimit", "options"],
      "additionalProperties": false
    },
    "gpus": {
      "type": "object",
      "properties": {
        "options": {
          "type": "array",
          "items": { "type": "integer" },
          "minItems": 1
        }
      },
      "required": ["options"],
      "additionalProperties": false
    },
    "maxInteractiveSessions": {
      "type": "integer",
      "minimum": 1
    }
  },
  "required": ["cores", "memoryGB"],
  "additionalProperties": false
}

=== opencadc/science-platform/skaha/src/test/resources/k8s-resources.json
{
  "cores": {
    "default": 1,
    "defaultRequest": 1,
    "defaultLimit": 8,
    "options": [
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11,
      12,
      13,
      14,
      15,
      16
    ]
  },
  "memoryGB": {
    "default": 1,
    "defaultRequest": 4,
    "defaultLimit": 32,
    "options": [
      1,
      2,
      4,
      6,
      8,
      10,
      12,
      14,
      16,
      20,
      24,
      26,
      28,
      30,
      32,
      36,
      40,
      44,
      48,
      56,
      64,
      80,
      92,
      112,
      128,
      140,
      170,
      192
    ]
  },
  "gpus": {
    "options": [
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11,
      12,
      13,
      14,
      15,
      16,
      17,
      18,
      19,
      20,
      21,
      22,
      23,
      24,
      25,
      26,
      27,
      28
    ]
  },
  "maxInteractiveSessions": 3
}
